package com.chronos.chronos.entity;

// @Entity tells JPA "this Java class maps to a database table"
// @Table tells JPA which table name to use
// @Getter @Setter are Lombok — generate getters and setters automatically
// @NoArgsConstructor generates an empty constructor (JPA requires this)
// @AllArgsConstructor generates a constructor with all fields

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "users")         // maps to the 'users' table in PostgreSQL
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder                       // Lombok — lets us do User.builder().name("x").build()
public class User {

    @Id
    // NONE means we are NOT using auto-increment
    // The UUID is generated by PostgreSQL (DEFAULT gen_random_uuid() in our SQL)
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // nullable = false matches our SQL's NOT NULL constraint
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    // unique = true matches our SQL's UNIQUE constraint
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    // We never expose this field in API responses (that's handled in DTOs later)
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // @CreationTimestamp tells Hibernate to automatically set this
    // to the current time when the row is first inserted
    // updatable = false means this value never changes after creation
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // @UpdateTimestamp automatically updates this every time the row changes
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
