ALTER TABLE jobs ALTER COLUMN status DROP DEFAULT;
ALTER TABLE jobs
    ALTER COLUMN status TYPE VARCHAR(20) USING status::TEXT,
    ALTER COLUMN type TYPE VARCHAR(20) USING type::TEXT;
ALTER TABLE execution_logs
    ALTER COLUMN status TYPE VARCHAR(20) USING status::TEXT;
DROP TYPE IF EXISTS job_status CASCADE;
DROP TYPE IF EXISTS job_type CASCADE;
DROP TYPE IF EXISTS log_status CASCADE;
ALTER TABLE jobs ALTER COLUMN status SET DEFAULT 'PENDING';
ALTER TABLE jobs ALTER COLUMN retry_count SET DEFAULT 0;
ALTER TABLE jobs ALTER COLUMN max_retries SET DEFAULT 3;
